In [6]:
import numpy as np 
a = np.array([1,2,3])
print(type(a))
print(a.shape)
print(a)
print(a[0], a[1], a[2])

<class 'numpy.ndarray'>
(3,)
[1 2 3]
1 2 3


In [9]:
b = np.array([[1, 2, 3],[4, 5, 6]])
print(b.shape)
c = np.array([ [1,2,3,4], [5,6,10,12], [6,8,9,1]  ])
print(c.shape)

(2, 3)
(3, 4)


In [14]:
# Numpy also provides many function to create arrays
z = np.zeros((4,6))
o = np.ones((2,5))
f = np.full((3,3),5)
e = np.eye(3)
r = np.random.random((4,4))
r

array([[0.95113361, 0.47561715, 0.63327893, 0.22808065],
       [0.13196644, 0.05001038, 0.64500654, 0.24542783],
       [0.62468476, 0.78952391, 0.47197644, 0.91439061],
       [0.71831124, 0.506354  , 0.01336906, 0.35038983]])

In [18]:
# Array indexing
a = np.array([[1,2,3,4], [5,8,9,7],[6,10,12,17]])
print(a)
b = a[:2,1:3]
print(b)
b[0,0] = 77
print(b)

[[ 1  2  3  4]
 [ 5  8  9  7]
 [ 6 10 12 17]]
[[2 3]
 [8 9]]
[[77  3]
 [ 8  9]]


In [20]:
# Boolean array indexing
a = np.array([[1,2],[3,4],[5,6]])
bool_ind = (a>2)
print(bool_ind)
print(a.dtype)

[[False False]
 [ True  True]
 [ True  True]]
int64


In [ ]:
# me
